/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as GamesReverbRouteImport } from './routes/games.reverb'
import { Route as GamesPanRouteImport } from './routes/games.pan'
import { Route as GamesFrequencyRouteImport } from './routes/games.frequency'
import { Route as GamesFilterTypeRouteImport } from './routes/games.filter-type'
import { Route as GamesEqCutRouteImport } from './routes/games.eq-cut'
import { Route as GamesEarEqRouteImport } from './routes/games.ear-eq'
import { Route as GamesDistortionRouteImport } from './routes/games.distortion'
import { Route as GamesDelayTimeRouteImport } from './routes/games.delay-time'
import { Route as GamesDbQuizRouteImport } from './routes/games.db-quiz'
import { Route as GamesDbProRouteImport } from './routes/games.db-pro'
import { Route as GamesCompressorReleaseRouteImport } from './routes/games.compressor-release'
import { Route as GamesCompressorRatioRouteImport } from './routes/games.compressor-ratio'
import { Route as GamesCompressorAttackRouteImport } from './routes/games.compressor-attack'
import { Route as GamesCompressionRouteImport } from './routes/games.compression'
import { Route as ForumCategoryRouteImport } from './routes/forum.$category'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ForumThreadIdRouteImport } from './routes/forum.thread.$id'
import { Route as AuthenticatedPostPostIdRouteImport } from './routes/_authenticated/post.$postId'
import { Route as AuthenticatedAdminLoopsRouteImport } from './routes/_authenticated/admin.loops'
import { Route as AuthenticatedAdminLogRouteImport } from './routes/_authenticated/admin.log'
import { Route as AuthenticatedAdminGlossaryRouteImport } from './routes/_authenticated/admin.glossary'
import { Route as AuthenticatedAdminForumRouteImport } from './routes/_authenticated/admin.forum'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'

const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesReverbRoute = GamesReverbRouteImport.update({
  id: '/games/reverb',
  path: '/games/reverb',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPanRoute = GamesPanRouteImport.update({
  id: '/games/pan',
  path: '/games/pan',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFrequencyRoute = GamesFrequencyRouteImport.update({
  id: '/games/frequency',
  path: '/games/frequency',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFilterTypeRoute = GamesFilterTypeRouteImport.update({
  id: '/games/filter-type',
  path: '/games/filter-type',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesEqCutRoute = GamesEqCutRouteImport.update({
  id: '/games/eq-cut',
  path: '/games/eq-cut',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesEarEqRoute = GamesEarEqRouteImport.update({
  id: '/games/ear-eq',
  path: '/games/ear-eq',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDistortionRoute = GamesDistortionRouteImport.update({
  id: '/games/distortion',
  path: '/games/distortion',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDelayTimeRoute = GamesDelayTimeRouteImport.update({
  id: '/games/delay-time',
  path: '/games/delay-time',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDbQuizRoute = GamesDbQuizRouteImport.update({
  id: '/games/db-quiz',
  path: '/games/db-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDbProRoute = GamesDbProRouteImport.update({
  id: '/games/db-pro',
  path: '/games/db-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCompressorReleaseRoute = GamesCompressorReleaseRouteImport.update({
  id: '/games/compressor-release',
  path: '/games/compressor-release',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCompressorRatioRoute = GamesCompressorRatioRouteImport.update({
  id: '/games/compressor-ratio',
  path: '/games/compressor-ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCompressorAttackRoute = GamesCompressorAttackRouteImport.update({
  id: '/games/compressor-attack',
  path: '/games/compressor-attack',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCompressionRoute = GamesCompressionRouteImport.update({
  id: '/games/compression',
  path: '/games/compression',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumCategoryRoute = ForumCategoryRouteImport.update({
  id: '/forum/$category',
  path: '/forum/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ForumThreadIdRoute = ForumThreadIdRouteImport.update({
  id: '/forum/thread/$id',
  path: '/forum/thread/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostPostIdRoute = AuthenticatedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLoopsRoute = AuthenticatedAdminLoopsRouteImport.update({
  id: '/admin/loops',
  path: '/admin/loops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLogRoute = AuthenticatedAdminLogRouteImport.update({
  id: '/admin/log',
  path: '/admin/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGlossaryRoute =
  AuthenticatedAdminGlossaryRouteImport.update({
    id: '/admin/glossary',
    path: '/admin/glossary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminForumRoute = AuthenticatedAdminForumRouteImport.update({
  id: '/admin/forum',
  path: '/admin/forum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand': typeof BrandRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/glossary': typeof GlossaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/presets': typeof PresetsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/forum/$category': typeof ForumCategoryRoute
  '/games/compression': typeof GamesCompressionRoute
  '/games/compressor-attack': typeof GamesCompressorAttackRoute
  '/games/compressor-ratio': typeof GamesCompressorRatioRoute
  '/games/compressor-release': typeof GamesCompressorReleaseRoute
  '/games/db-pro': typeof GamesDbProRoute
  '/games/db-quiz': typeof GamesDbQuizRoute
  '/games/delay-time': typeof GamesDelayTimeRoute
  '/games/distortion': typeof GamesDistortionRoute
  '/games/ear-eq': typeof GamesEarEqRoute
  '/games/eq-cut': typeof GamesEqCutRoute
  '/games/filter-type': typeof GamesFilterTypeRoute
  '/games/frequency': typeof GamesFrequencyRoute
  '/games/pan': typeof GamesPanRoute
  '/games/reverb': typeof GamesReverbRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/forum/': typeof ForumIndexRoute
  '/games/': typeof GamesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/admin/glossary': typeof AuthenticatedAdminGlossaryRoute
  '/admin/log': typeof AuthenticatedAdminLogRoute
  '/admin/loops': typeof AuthenticatedAdminLoopsRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/forum/thread/$id': typeof ForumThreadIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand': typeof BrandRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/glossary': typeof GlossaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/presets': typeof PresetsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/forum/$category': typeof ForumCategoryRoute
  '/games/compression': typeof GamesCompressionRoute
  '/games/compressor-attack': typeof GamesCompressorAttackRoute
  '/games/compressor-ratio': typeof GamesCompressorRatioRoute
  '/games/compressor-release': typeof GamesCompressorReleaseRoute
  '/games/db-pro': typeof GamesDbProRoute
  '/games/db-quiz': typeof GamesDbQuizRoute
  '/games/delay-time': typeof GamesDelayTimeRoute
  '/games/distortion': typeof GamesDistortionRoute
  '/games/ear-eq': typeof GamesEarEqRoute
  '/games/eq-cut': typeof GamesEqCutRoute
  '/games/filter-type': typeof GamesFilterTypeRoute
  '/games/frequency': typeof GamesFrequencyRoute
  '/games/pan': typeof GamesPanRoute
  '/games/reverb': typeof GamesReverbRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/forum': typeof ForumIndexRoute
  '/games': typeof GamesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/admin/glossary': typeof AuthenticatedAdminGlossaryRoute
  '/admin/log': typeof AuthenticatedAdminLogRoute
  '/admin/loops': typeof AuthenticatedAdminLoopsRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/forum/thread/$id': typeof ForumThreadIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/brand': typeof BrandRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/glossary': typeof GlossaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/presets': typeof PresetsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/forum/$category': typeof ForumCategoryRoute
  '/games/compression': typeof GamesCompressionRoute
  '/games/compressor-attack': typeof GamesCompressorAttackRoute
  '/games/compressor-ratio': typeof GamesCompressorRatioRoute
  '/games/compressor-release': typeof GamesCompressorReleaseRoute
  '/games/db-pro': typeof GamesDbProRoute
  '/games/db-quiz': typeof GamesDbQuizRoute
  '/games/delay-time': typeof GamesDelayTimeRoute
  '/games/distortion': typeof GamesDistortionRoute
  '/games/ear-eq': typeof GamesEarEqRoute
  '/games/eq-cut': typeof GamesEqCutRoute
  '/games/filter-type': typeof GamesFilterTypeRoute
  '/games/frequency': typeof GamesFrequencyRoute
  '/games/pan': typeof GamesPanRoute
  '/games/reverb': typeof GamesReverbRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/forum/': typeof ForumIndexRoute
  '/games/': typeof GamesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/forum': typeof AuthenticatedAdminForumRoute
  '/_authenticated/admin/glossary': typeof AuthenticatedAdminGlossaryRoute
  '/_authenticated/admin/log': typeof AuthenticatedAdminLogRoute
  '/_authenticated/admin/loops': typeof AuthenticatedAdminLoopsRoute
  '/_authenticated/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/forum/thread/$id': typeof ForumThreadIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brand'
    | '/community'
    | '/courses'
    | '/forbidden'
    | '/glossary'
    | '/leaderboard'
    | '/presets'
    | '/chat'
    | '/moderation'
    | '/notifications'
    | '/profile'
    | '/auth/reset-password'
    | '/courses/$slug'
    | '/forum/$category'
    | '/games/compression'
    | '/games/compressor-attack'
    | '/games/compressor-ratio'
    | '/games/compressor-release'
    | '/games/db-pro'
    | '/games/db-quiz'
    | '/games/delay-time'
    | '/games/distortion'
    | '/games/ear-eq'
    | '/games/eq-cut'
    | '/games/filter-type'
    | '/games/frequency'
    | '/games/pan'
    | '/games/reverb'
    | '/learn/$slug'
    | '/u/$username'
    | '/forum/'
    | '/games/'
    | '/learn/'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/forum'
    | '/admin/glossary'
    | '/admin/log'
    | '/admin/loops'
    | '/post/$postId'
    | '/forum/thread/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brand'
    | '/community'
    | '/courses'
    | '/forbidden'
    | '/glossary'
    | '/leaderboard'
    | '/presets'
    | '/chat'
    | '/moderation'
    | '/notifications'
    | '/profile'
    | '/auth/reset-password'
    | '/courses/$slug'
    | '/forum/$category'
    | '/games/compression'
    | '/games/compressor-attack'
    | '/games/compressor-ratio'
    | '/games/compressor-release'
    | '/games/db-pro'
    | '/games/db-quiz'
    | '/games/delay-time'
    | '/games/distortion'
    | '/games/ear-eq'
    | '/games/eq-cut'
    | '/games/filter-type'
    | '/games/frequency'
    | '/games/pan'
    | '/games/reverb'
    | '/learn/$slug'
    | '/u/$username'
    | '/forum'
    | '/games'
    | '/learn'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/forum'
    | '/admin/glossary'
    | '/admin/log'
    | '/admin/loops'
    | '/post/$postId'
    | '/forum/thread/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/brand'
    | '/community'
    | '/courses'
    | '/forbidden'
    | '/glossary'
    | '/leaderboard'
    | '/presets'
    | '/_authenticated/chat'
    | '/_authenticated/moderation'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/auth/reset-password'
    | '/courses/$slug'
    | '/forum/$category'
    | '/games/compression'
    | '/games/compressor-attack'
    | '/games/compressor-ratio'
    | '/games/compressor-release'
    | '/games/db-pro'
    | '/games/db-quiz'
    | '/games/delay-time'
    | '/games/distortion'
    | '/games/ear-eq'
    | '/games/eq-cut'
    | '/games/filter-type'
    | '/games/frequency'
    | '/games/pan'
    | '/games/reverb'
    | '/learn/$slug'
    | '/u/$username'
    | '/forum/'
    | '/games/'
    | '/learn/'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/forum'
    | '/_authenticated/admin/glossary'
    | '/_authenticated/admin/log'
    | '/_authenticated/admin/loops'
    | '/_authenticated/post/$postId'
    | '/forum/thread/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BrandRoute: typeof BrandRoute
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  GlossaryRoute: typeof GlossaryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PresetsRoute: typeof PresetsRoute
  ForumCategoryRoute: typeof ForumCategoryRoute
  GamesCompressionRoute: typeof GamesCompressionRoute
  GamesCompressorAttackRoute: typeof GamesCompressorAttackRoute
  GamesCompressorRatioRoute: typeof GamesCompressorRatioRoute
  GamesCompressorReleaseRoute: typeof GamesCompressorReleaseRoute
  GamesDbProRoute: typeof GamesDbProRoute
  GamesDbQuizRoute: typeof GamesDbQuizRoute
  GamesDelayTimeRoute: typeof GamesDelayTimeRoute
  GamesDistortionRoute: typeof GamesDistortionRoute
  GamesEarEqRoute: typeof GamesEarEqRoute
  GamesEqCutRoute: typeof GamesEqCutRoute
  GamesFilterTypeRoute: typeof GamesFilterTypeRoute
  GamesFrequencyRoute: typeof GamesFrequencyRoute
  GamesPanRoute: typeof GamesPanRoute
  GamesReverbRoute: typeof GamesReverbRoute
  LearnSlugRoute: typeof LearnSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ForumIndexRoute: typeof ForumIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ForumThreadIdRoute: typeof ForumThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/reverb': {
      id: '/games/reverb'
      path: '/games/reverb'
      fullPath: '/games/reverb'
      preLoaderRoute: typeof GamesReverbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/pan': {
      id: '/games/pan'
      path: '/games/pan'
      fullPath: '/games/pan'
      preLoaderRoute: typeof GamesPanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/frequency': {
      id: '/games/frequency'
      path: '/games/frequency'
      fullPath: '/games/frequency'
      preLoaderRoute: typeof GamesFrequencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/filter-type': {
      id: '/games/filter-type'
      path: '/games/filter-type'
      fullPath: '/games/filter-type'
      preLoaderRoute: typeof GamesFilterTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/eq-cut': {
      id: '/games/eq-cut'
      path: '/games/eq-cut'
      fullPath: '/games/eq-cut'
      preLoaderRoute: typeof GamesEqCutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/ear-eq': {
      id: '/games/ear-eq'
      path: '/games/ear-eq'
      fullPath: '/games/ear-eq'
      preLoaderRoute: typeof GamesEarEqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/distortion': {
      id: '/games/distortion'
      path: '/games/distortion'
      fullPath: '/games/distortion'
      preLoaderRoute: typeof GamesDistortionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/delay-time': {
      id: '/games/delay-time'
      path: '/games/delay-time'
      fullPath: '/games/delay-time'
      preLoaderRoute: typeof GamesDelayTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/db-quiz': {
      id: '/games/db-quiz'
      path: '/games/db-quiz'
      fullPath: '/games/db-quiz'
      preLoaderRoute: typeof GamesDbQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/db-pro': {
      id: '/games/db-pro'
      path: '/games/db-pro'
      fullPath: '/games/db-pro'
      preLoaderRoute: typeof GamesDbProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/compressor-release': {
      id: '/games/compressor-release'
      path: '/games/compressor-release'
      fullPath: '/games/compressor-release'
      preLoaderRoute: typeof GamesCompressorReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/compressor-ratio': {
      id: '/games/compressor-ratio'
      path: '/games/compressor-ratio'
      fullPath: '/games/compressor-ratio'
      preLoaderRoute: typeof GamesCompressorRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/compressor-attack': {
      id: '/games/compressor-attack'
      path: '/games/compressor-attack'
      fullPath: '/games/compressor-attack'
      preLoaderRoute: typeof GamesCompressorAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/compression': {
      id: '/games/compression'
      path: '/games/compression'
      fullPath: '/games/compression'
      preLoaderRoute: typeof GamesCompressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$category': {
      id: '/forum/$category'
      path: '/forum/$category'
      fullPath: '/forum/$category'
      preLoaderRoute: typeof ForumCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forum/thread/$id': {
      id: '/forum/thread/$id'
      path: '/forum/thread/$id'
      fullPath: '/forum/thread/$id'
      preLoaderRoute: typeof ForumThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post/$postId': {
      id: '/_authenticated/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof AuthenticatedPostPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/loops': {
      id: '/_authenticated/admin/loops'
      path: '/admin/loops'
      fullPath: '/admin/loops'
      preLoaderRoute: typeof AuthenticatedAdminLoopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/log': {
      id: '/_authenticated/admin/log'
      path: '/admin/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AuthenticatedAdminLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/glossary': {
      id: '/_authenticated/admin/glossary'
      path: '/admin/glossary'
      fullPath: '/admin/glossary'
      preLoaderRoute: typeof AuthenticatedAdminGlossaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/forum': {
      id: '/_authenticated/admin/forum'
      path: '/admin/forum'
      fullPath: '/admin/forum'
      preLoaderRoute: typeof AuthenticatedAdminForumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminForumRoute: typeof AuthenticatedAdminForumRoute
  AuthenticatedAdminGlossaryRoute: typeof AuthenticatedAdminGlossaryRoute
  AuthenticatedAdminLogRoute: typeof AuthenticatedAdminLogRoute
  AuthenticatedAdminLoopsRoute: typeof AuthenticatedAdminLoopsRoute
  AuthenticatedPostPostIdRoute: typeof AuthenticatedPostPostIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminForumRoute: AuthenticatedAdminForumRoute,
  AuthenticatedAdminGlossaryRoute: AuthenticatedAdminGlossaryRoute,
  AuthenticatedAdminLogRoute: AuthenticatedAdminLogRoute,
  AuthenticatedAdminLoopsRoute: AuthenticatedAdminLoopsRoute,
  AuthenticatedPostPostIdRoute: AuthenticatedPostPostIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BrandRoute: BrandRoute,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  GlossaryRoute: GlossaryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PresetsRoute: PresetsRoute,
  ForumCategoryRoute: ForumCategoryRoute,
  GamesCompressionRoute: GamesCompressionRoute,
  GamesCompressorAttackRoute: GamesCompressorAttackRoute,
  GamesCompressorRatioRoute: GamesCompressorRatioRoute,
  GamesCompressorReleaseRoute: GamesCompressorReleaseRoute,
  GamesDbProRoute: GamesDbProRoute,
  GamesDbQuizRoute: GamesDbQuizRoute,
  GamesDelayTimeRoute: GamesDelayTimeRoute,
  GamesDistortionRoute: GamesDistortionRoute,
  GamesEarEqRoute: GamesEarEqRoute,
  GamesEqCutRoute: GamesEqCutRoute,
  GamesFilterTypeRoute: GamesFilterTypeRoute,
  GamesFrequencyRoute: GamesFrequencyRoute,
  GamesPanRoute: GamesPanRoute,
  GamesReverbRoute: GamesReverbRoute,
  LearnSlugRoute: LearnSlugRoute,
  UUsernameRoute: UUsernameRoute,
  ForumIndexRoute: ForumIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  ForumThreadIdRoute: ForumThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
